### ISSUE TITLE
Impossible to click on selected button

### ISSUE THREAD

**Issue by Miepee** [Skwodo/skwodo.com#4]
![image](https://user-images.githubusercontent.com/38186597/185764923-c94b15c8-43a1-4302-9f9c-be2ee874bf93.png)

Call there is not treated as a button, I cannot click it. For consistency it would be nice if I was able to click it.

**Comment by lemon-sh** [comment]
it works for me
![image](https://user-images.githubusercontent.com/26277478/185766958-83c1b3d7-9f43-4d77-85db-8c06d5f991ee.png)

**Comment by Miepee** [comment]
Sorry, I meant that if you're on the Call page:
![image](https://user-images.githubusercontent.com/38186597/185784814-2b220693-b932-4215-99fe-e9bb9182a0c6.png)
![image](https://user-images.githubusercontent.com/38186597/185785033-90b9f3b8-ca22-4204-a362-ddbb446f73a3.png)

**Comment by lemon-sh** [comment]
why you'd want to click "call" if you're already on "call" is beyond my understanding

**Comment by Skwodo** [comment]
I don't see a reason for clicking a button for a page you're already on.

**Comment by Miepee** [comment]
As mentioned above, it would be nice for consistency. It's weird when I suddenly am able to select the text of a button, instead of clicking it.

**Comment by Skwodo** [comment]
I'm just gonna leave it as it is for now
