### ISSUE TITLE
Missing commas

### ISSUE THREAD

**Issue by Miepee** [Skwodo/skwodo.com#5]
> to write anything in any language is nonexistent at the moment so yea.

There are commas missing at the end. Something more like `to write anything in any langauge is nonexistant at the moment, so... yeah.` is more readable.

**Comment by Skwodo** [comment]
Matter of opinion.

**Comment by Miepee** [comment]
I disagree that it's a subjective thing. The way it is written right now, make it more difficult to read in what the intention was.
That, and it violates grammar rules last time I checked.
