### ISSUE TITLE
Inconsistent capitalization in "Website is done" blog

### ISSUE THREAD

**Issue by Miepee** [Skwodo/skwodo.com#8]
![image](https://user-images.githubusercontent.com/38186597/185804104-ec2d997a-5952-48a2-b3b7-0e50b4f80e4e.png)
Ccapitalization is here inconsistent
(U, l, U, l, U)

**Comment by Miepee** [comment]
Oh, also this
![image](https://user-images.githubusercontent.com/38186597/185804150-eaa94336-5f16-4ca2-b8c9-d3be67d354be.png)

**Comment by Skwodo** [comment]
Fixed
